### ISSUE TITLE
Output columns

### ISSUE THREAD

**Issue by hiddearend** [xihuiwu/GPMF_extract#1]
Hi, thanks for this great repo. 

Could you please explain me what each of the outcome columns mean in the gps5 file?

**Comment by xihuiwu** [comment]
Hello,

The first column is the relative timestamp. Rest columns are latitude, longitude, altitude (WGS 84), 2D ground speed, and 3D speed.

Units are sec, degree, degree, meter, meter/sec, meter/sec.
